### PR TITLE
ISSUE-217

### LINKED ISSUE #217: Server seems to crash when opening mp4(or large) files
Crash report: https://pastebin.com/YxMCnXQd

The server seems to crash when opening a mp4 file from local storage, unsure about cause.

### PR DESCRIPTION
**Pull request by aspacca**
Fix #217

### CODE REVIEW

File: server/handlers.go [hunk 1]
```diff
@@ -892,6 +895,16 @@ func (s *Server) getHandler(w http.ResponseWriter, r *http.Request) {
 	w.Header().Set("Content-Disposition", fmt.Sprintf("%s; filename=\"%s\"", disposition, filename))
 	w.Header().Set("Connection", "keep-alive")
 
+	if w.Header().Get("Range") == "" {
```
Comment (kiska3) [inline server/handlers.go]: > # github.com/dutchcoders/transfer.sh/server
> server/handlers.go:898:1: syntax error: unexpected <<, expecting }

When I try to: `go build -o transfersh main.go`

Was there anything else you wanted me to try on the server?
